- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- pubspec.lock
- pubspec.yaml
issue #9 fixed ,
pls review the code.
> added onTap on listtile and fixed the shared alarm Bug.

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/GoogleService-Info.plist
firebase was not initialised for ios 
These are the logs(no issues detected) and the application after running the project locally :)
> Firebase configured for ulitmate_alarm_clock

- android/gradle.properties
> Explicit path of java jdk removed

- ios/Runner/Info.plist
> Configured camera permission for ios

- android/gradle.properties
- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/screen_activity_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/shake_to_dismiss_tile.dart
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- macos/Podfile
solved #12 
I added done button to repeat and screen activity dialogue only as it was already present to other dialogues
> Done button dialogue

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Issue template added (bug.yaml and feature_request.yml)
- path (.github/ISSUE_TEMPLATE)
> Issue template added

- .github/pull_request_template.md
- Pull request template added 
- Path (.github)
> pull request template added

- ios/Podfile.lock
- lib/app/modules/home/controllers/home_controller.dart
solved  #23 
All the details are explained with comments in pr itself
> Ringing in Time issue solved

- lib/app/modules/addOrUpdateAlarm/views/snooze_duration_tile.dart
> UI - Done button added to snooze tile

- lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
To improve code refactoring, I've added a new `dayTile` widget at the end of the `repeat_tile.dart` file. Also, I've added the trailing commas for better code formatting. 
- Instead of writing the `InkWell` widget for 7 days, I've added the `dayTile` widget to improve code refactoring, and for better readability. 
- Added trailing commas so that the code gets more readable with better formatting. 
NA
<a href="https://ibb.co/k4KQdyN"><img src="https://i.ibb.co/n7rzW0x/SCR-20230825-jyt.png" alt="SCR-20230825-jyt" border="0" width="250" height="500"></a>
> Added dayTile widget for code refactoring and improved formatting

- lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
> added the off text on the label tile when the label is empty

- lib/app/modules/home/views/home_view.dart
> Made the icons fade when alarm is off

- lib/app/modules/home/views/home_view.dart
> solved the overflow in the tile

- lib/app/modules/home/controllers/home_controller.dart
- lib/app/modules/home/views/home_view.dart
I've implemented the `SliverAppBar` on the `HomePage` for better user experience. Now, when the user scrolls, the height of the `AppBar`will reduce to some extent. The size of both texts will also be reduced and the settings icon will be hidden. 
- Implemented `SliverAppBar` on the `HomePage`. 
- `Settings` icon will disappear on scrolling down. 
- Text size will be reduced on scrolling down. 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/9a02b883-9bd8-4907-b0d5-b57fa860b444
> Feature: Implemented SliverAppBar on HomePage

- lib/app/modules/settings/views/weather_api.dart
I've implemented the change in the design of the `Get Key` button. Now it doesn't look as if it's disabled. I've implemented the `OutlinedButton` to achieve the desired results. 
- Changed the `TextButton` to `OutlinedButton`.
<a href="https://ibb.co/svMvTGT"><img src="https://i.ibb.co/PZfZ2n2/SCR-20230907-syi.png" alt="SCR-20230907-syi" border="0" width="250" height="500"></a>
> Feature: Implemented the change in design of Get Key button

- lib/app/data/providers/secure_storage_provider.dart
- lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
- lib/app/modules/home/controllers/home_controller.dart
- lib/app/modules/home/views/home_view.dart
- lib/app/modules/settings/controllers/settings_controller.dart
- lib/app/modules/settings/views/enable_sorted_alarm_list.dart
- lib/app/modules/settings/views/settings_view.dart
- lib/app/modules/settings/views/weather_api.dart
I've implemented the `Sorted Alarm List` feature in the HomeView. Now users can turn on this feature as per their preference in the `SettingsView` through the Switch present there. If turned **ON** the alarms will be sorted in the order of `AlarmTime` otherwise the alarms will be sorted in order of `Active and AlarmTime`. 
- I've made a new RxBool variable in the `HomeController`, and I'm doing sorting in the `initStream` method. 
- I've implemented the new methods for reading and writing the `isSortedAlarmListValue` in the `secure_storage_provider.dart`. 
- I've made a new file named `enabled_sorted_alarm_list` for toggling the value of `isSortedAlarmListValue` in the views of Settings. 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/c721e29b-9319-4329-8ed1-544e9c13f2 …
> Feature: Implemented the Sorted Alarm List

- lib/app/modules/settings/views/settings_view.dart
added haptic to appbar in setting:)
yet some work is remaining fixes #52
> haptic bug

- lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
- pubspec.lock
- pubspec.yaml
I've implemented the snack bar to the `Label Tile` when the user enters whitespace first. So the snack bar will be displayed at the top of the screen when the user enters whitespace as a character first in the Label Tile name. 
- I've used `another_flushbar` to display the snack bar as the normal snack bar and `Get.snackbar()` aren't shown in focus with the `defaultDialog`. They are in the background of the `defaultDialog` resulting in poor attention gaining for them. `Flushbar` is displayed in focus with the `defaultDialog`.  
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/31ac8dcf-7bb9-487f-9896-7aaf9df58851
> Feature: Implemented snackbar to the Label Tile

- lib/app/modules/settings/views/theme_value_tile.dart
Fixes #84
(Enable Light Mode) Switch button color has changed.
> (Enable Light Mode) Switch button color changed.

- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- pubspec.lock
> In Add or update Alarm view, the (Discard changes) Leave button color changed to red

- lib/app/modules/settings/views/settings_view.dart
- pubspec.lock
> overflow fixed

- lib/app/modules/settings/controllers/settings_controller.dart
- lib/app/modules/settings/views/theme_value_tile.dart
- lib/app/modules/settings/views/weather_api.dart
- lib/app/utils/constants.dart
I've implemented the dialog for updating the `API Key`. So if the user hasn't added their `API Key`, then the dialog will prompt them to add, and if they have already added the `API Key`, then it will prompt them to update it. 
- Implemented a new `enum` named `WeatherKeyState` which consists of
- **add** (wants to add for the first time)
- **update** (wants to update)
- **saveAdded** (added successfully)
- **saveUpdated** (updated successfully)
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/319b931c-b138-49ec-8496-30a3956ad3a7
> Feature: Implemented the OpenWeatherMap API Key Dialog

- lib/main.dart
> #94 : Proposed the change in the status bar colour for better UI

- lib/app/modules/home/views/home_view.dart
Changed the progress indicator colour
The circle Progress indicator had same background and active colour which posed difficult to see if it is loading or not 
so i changes one of the two colour for better viewing
> Bug:#110 changed progress indicator color for better view

- README.md
I've added comprehensive documentation covering the important aspects of the application. I've added the following points to the documentation:- 
- GetX Pattern
- Database Schema
- Installation & Setup
- User Interface & Features
- Contribution Guidelines
- Future Plans
- Community
- Flutter
- Changed the `README.md` file
_No response_
> Docs: Added the documentation

- lib/app/modules/settings/views/enable_haptic_feedback.dart
- lib/app/modules/settings/views/enable_sorted_alarm_list.dart
- lib/app/modules/settings/views/google_sign_in.dart
- lib/app/modules/settings/views/theme_value_tile.dart
- lib/app/modules/settings/views/weather_api.dart
- [ x] Code follows the established coding style guidelines
- [x ] All tests are passing
> Bug Fix: Settings page element alignment

- .github/dependabot.yaml
- lib/app/modules/addOrUpdateAlarm/views/location_activity_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/maths_challenge_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/qr_bar_code_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/screen_activity_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/shake_to_dismiss_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
- lib/app/utils/utils.dart
Implemented a dedicated function named 'showModal' within the utilities class/folder.
> Added 'showModal' Utility function for info (i) buttons on add alarm screen

- lib/app/modules/About/views/about_view.dart
- lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/19a33b1a-01d5-493c-824b-5bd86fcccd95
> Theme Controller added to About Section

- lib/app/modules/About/bindings/about_binding.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/930b2526-0fdb-4456-8c2d-faf093e105c5
> About controller corrected in about_binding.dart

- README.md
- lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- pubspec.lock
- windows/runner/flutter_window.cpp
Alternate option to add time using textfield has been added. You can toggle between textfields and datepicker by tapping once.
> Input time in textFields using keyboard

- lib/app/modules/home/views/home_view.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/1c73c9c2-9a8e-47f3-8df5-cb2108781174
> Update color feature added in delete icon button in Multiple Alarm delete option

- lib/app/modules/settings/views/custom_ringtone.dart
Outlined button text now includes a controller in custom ringtones to change "choose ringtone to change ringtone" if a user adds a ringtone from the device.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/4542db30-a43a-4ebe-9689-8b9c0e746335
> Controller added to Outlined button text in custom ringtone

- lib/app/data/providers/secure_storage_provider.dart
- lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/home/views/home_view.dart
- lib/app/modules/settings/controllers/settings_controller.dart
- lib/app/modules/settings/views/enable_24Hour_format.dart
- lib/app/modules/settings/views/settings_view.dart
- lib/app/utils/utils.dart
Added 24 hour format option to the application
https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/9207f433-b57c-4332-bcc0-4091e7d1a52c
> 24 hours format added

- lib/app/modules/alarmRing/views/alarm_ring_view.dart
i have increased the button size please review the changes
#211
> increase snooze button size

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- macos/Flutter/GeneratedPluginRegistrant.swift
Renamed the application to Ulitmate Alarm Clock
> Renamed the application to Ultimate Alarm Clock

- lib/app/modules/about/views/about_view.dart
Changed the text and version number
#214
> Changed the text and version in the about section

- pubspec.yaml
> Changed the version to 0.5.0

- pubspec.yaml
As some of the contributors were facing an issue regarding the `PopScope` widget not working in their environment, I've upgraded the Flutter and Dart SDK version constraints in the `pubspec.yaml` file.
- Updated the Flutter and Dart SDK version constraints in the `pubspec.yaml` file.
> Refactor: Updated the flutter and dart sdk versions in pubspec file

- lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart
Previously, when the user entered any invalid character or cleared everything in the input time field, the app throws an exception in the terminal. 
In this PR, I've implemented the error handling in `InputTimeController` and as a result, the app catches the exception.
- Implemented error handling in `InputTimeController`.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/0d7d7f51-aa7c-4e73-844a-68536163cd28
> Refactor: Implemented error handling in input time controller

- lib/app/data/models/alarm_model.dart
- lib/app/data/models/alarm_model.g.dart
- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/addOrUpdateAlarm/views/note.dart
- lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart
- lib/app/modules/alarmRing/views/alarm_ring_view.dart
- lib/app/utils/utils.dart
- pubspec.lock
- pubspec.yaml
Added the note feature while setting a new alarm
Previews:
> Add Note feature

- CONTRIBUTING.md
In this PR, I have added the `CONTRIBUTING.md` file to provide guidelines for contributors. The file outlines the process for contributing to the Ultimate Alarm Clock project, including forking, cloning, branch creation, making changes, testing, documentation updates, committing, and submitting pull requests. Additionally, it includes guidelines for contributors and reporting issues.
- Added `CONTRIBUTING.md` file to the project root.
- Detailed steps for contributing, including forking, cloning, branch creation, and submitting pull requests.
- Guidelines for contributors, code review, and handling issues.
> Docs: Added the CONTRIBUTING file

- lib/app/routes/app_pages.dart
Fixes #279 
Commented the redundancy out
> Fixes #279 , Redundant GetPages() in app_pages.dart

- lib/app/modules/settings/views/language_menu.dart
- pubspec.lock
In change Language dropdown menu button there is some pixel overflowed because of padding.
I have removed right padding of that button
- [X ] Tests have been added or updated to cover the changes
- [X ] Code follows the established coding style guidelines
- [X ] All tests are passing
> fix: pixel overflow in change language dropdown menu

- lib/app/modules/settings/views/enable_24Hour_format.dart
- lib/app/modules/settings/views/enable_haptic_feedback.dart
- lib/app/modules/settings/views/enable_sorted_alarm_list.dart
- lib/app/modules/settings/views/theme_value_tile.dart
- lib/app/modules/settings/views/weather_api.dart
fixed pixel overflow occured on selecting other languages.
wrap text widget with expanded widget which provide flexibility to expand.
> fix: overflow on selecting other languages

- lib/app/modules/home/views/home_view.dart
> fix: text alignment

- lib/app/modules/home/views/home_view.dart
- lib/app/modules/settings/views/settings_view.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/d8a1a949-91d3-47d4-a1f9-61590d3556a1
> fix: settings navigation

- lib/app/modules/home/views/home_view.dart
Changed the height of the drawer's header(made it responsive) Changed the font sizes,
Added a divider to make it more visually appealing
Changed the height of the drawer's header(made it responsive)
Changed the font sizes,
Added a divider to make it more visually appealing
A better space efficient drawer,
More features can be added to the drawer menu 
Before:
After:
> Improvement: Optimization of Drawer's header

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/app/data/models/alarm_model.dart
- lib/app/data/models/alarm_model.g.dart
- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/addOrUpdateAlarm/views/pedometer_challenge_tile.dart
- lib/app/modules/alarmChallenge/controllers/alarm_challenge_controller.dart
- lib/app/modules/alarmChallenge/views/alarm_challenge_view.dart
- lib/app/modules/alarmChallenge/views/pedometer_challenge_view.dart
- lib/app/modules/home/views/home_view.dart
- lib/app/utils/utils.dart
- pubspec.lock
- pubspec.yaml
This PR adds a pedometer challenge feature to enhance user engagement and promote a healthier morning routine. The feature requires users to walk a certain number of steps to turn off the alarm, adding an element of physical activity to the waking-up process.
- Set a configurable step count that users must achieve to dismiss the alarm.
- Utilize the pedometer package to accurately track the user's steps.
- Define a time window during which users must complete the steps challenge.
- Allow users to enable/disable the pedometer challenge and adjust step count targets in the `AddOrUpdateAlarmView`.
- Added the [pedometer](https://pub.dev/packages/pedometer) dependency to accurately track the user's steps.
- Added the uses-permission for `ACTIVITY_RECOGNITION` in the `AndroidManifest.xml` …
> Feature: Implemented Pedometer Challenge

- lib/app/modules/bottomNavigationBar/controllers/bottom_navigation_bar_controller.dart
- lib/app/modules/bottomNavigationBar/views/bottom_navigation_bar_view.dart
- lib/app/modules/settings/views/enable_haptic_feedback.dart
- lib/app/modules/stopwatch/bindings/stopwatch_bindings.dart
- lib/app/modules/stopwatch/controllers/stopwatch_controller.dart
- lib/app/modules/stopwatch/views/stopwatch_view.dart
- lib/app/routes/app_pages.dart
- lib/app/routes/app_routes.dart
view and controller are on seperate pages
> Stopwatch and controller

- lib/app/data/providers/get_storage_provider.dart
- lib/app/data/providers/secure_storage_provider.dart
- lib/app/modules/settings/controllers/settings_controller.dart
- lib/app/modules/settings/views/language_menu.dart
I have wrapped Dropdown menu with observable(Obx), and created a variable stores the key of language, updating and saved on changing the language. Whenever you come again in settings it retrieve the key of the last saved language and shows the language that belongs to the key.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/71c8a107-324e-435c-9d0f-65e1bf5e0a4a
> feature: always show current language

- .github/hooks/pre_commit.sh
- CONTRIBUTING.md
I have added the pre-commit hooks for improved code formatting. With this, on each commit the executed bash script will append missing required trailing commas, and format the files. 
These changes are done for improved code consistency and readability. 
To activate the pre-commit hooks, contributors may refer to the newly added `Activating Pre-Commit Hooks` section in the CONTRIBUTING.md file. 
- Added `pre_commit.sh` in the `.github/hooks` directory. 
- Added the `Activating Pre-Commit Hooks` section in the `CONTRIBUTING.md` file.
> Feature: Added Pre-Commit Hooks for Improved Formatting

- lib/app/modules/stopwatch/views/stopwatch_view.dart
- lib/app/modules/timer/views/timer_view.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/5907720d-7bcd-453b-8a30-e027e40d367c
> resolved Shakey counter for stopwatch and timer  

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/timer/views/timer_view.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/a9570b3f-7595-4cf0-b5f8-7c38c70ffe49
> Updated alarm timer selector

- lib/app/modules/stopwatch/views/stopwatch_view.dart
- lib/app/modules/timer/views/timer_view.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/91d62246-066f-4991-846e-dbd5632d9a3f
> fixed menu icon for stopwatch and timer page

- lib/app/modules/home/views/home_view.dart
- lib/app/modules/stopwatch/views/stopwatch_view.dart
- lib/app/modules/timer/views/timer_view.dart
- lib/app/utils/end_drawer.dart
Any developer can now call in endDrawer by buildEndDrawer(context), instead of writing the entire code, making our codebase organised and neat.
I have updated this in all three screens too.
> Better way of writing code.

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/ascending_volume.dart
- lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/maths_challenge_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/note.dart
- lib/app/modules/addOrUpdateAlarm/views/qr_bar_code_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/quote_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/shared_alarm_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
- lib/app/utils/language.dart
- lib/app/utils/languages/french_translations.dart
- lib/app/utils/languages/german_translations.dart
- lib/app/utils/languages/russian_translations.dart
- lib/app/utils/languages/spanish_translations.dart
Fixed the UI related bugs as described in #376 
- Made the motivational quote tile responsive
- Fixed the save, okay, cancel buttons' colors and text styles
- Changes the Label and Note tiles' Dialog box titles
UI related fixes in tiles and buttons in the AddOrUpdateAlarm view.
> Fixed UI related bugs in Add or update alarm screen

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/addOrUpdateAlarm/views/delete_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/shared_alarm_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/shared_users_tile.dart
- lib/app/modules/settings/controllers/settings_controller.dart
- lib/app/modules/settings/views/google_sign_in.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
When signing in through the add or update alarm screen, the shared alarm screen does not reflect the login state change.
Added a listener to the userModel in add_or_update_alarm_controller.dart that modifies the userModel after a change in login state.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/75253653/03ec64c5-d772-495e-a141-f5a95c3eeba2
> fix: google-sign in not persisting

- lib/app/modules/home/views/home_view.dart
When changing the language settings and attempting to put an alarm on hold to delete it, the top navigation user interface (UI) experiences overflow issues. This results in a display problem where elements extend beyond the expected boundaries, making it challenging for users to interact with the application effectively.
> fixed overflow error

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/choose_ringtone_tile.dart
hey @MarkisDev , I just realized that the ringtone counter wasn't decrementing when uploading a new ringtone for the same alarm. I don't know how I missed this case but I've added the required code to fix it. Sorry for any inconvenience this may have caused!
completes PR #421 
**Issue:**
https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/9191e6f0-cabe-4e58-adc2-fe7b94210df2
**fix:**
https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/8bc5ecaa-6a9c-4455-b447-15c964b3d50b
> ringtone counter final

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/utils/language.dart
- lib/app/utils/languages/french_translations.dart
- lib/app/utils/languages/german_translations.dart
- lib/app/utils/languages/russian_translations.dart
- lib/app/utils/languages/spanish_translations.dart
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/36afef4a-9cb3-4c96-9e25-2b78d900397a
> fix: duplicate ringtone

- lib/app/modules/addOrUpdateAlarm/views/choose_ringtone_tile.dart
- lib/app/modules/bottomNavigationBar/views/bottom_navigation_bar_view.dart
- lib/app/utils/audio_utils.dart
- pubspec.lock
Description
when playing a ringtone from choose a ringtone it was possible to play but not stop it, but with this change that problem is fixed
Proposed Changes
The Audio Utils file had some problems in previewCustomSound() method .
In the updated method isPreviewing is only set to true once, after the sound has started playing. This should ensure that isPreviewing is only true when a sound is actually playing
Fixes https://github.com/CCExtractor/ultimate_alarm_clock/issues/455
Checklist
> Fixed issue Ringtone continues to play even after stopping 

- lib/app/utils/constants.dart
Added a border to increase readabiity keeping in mind that the primary color is preserved.
> Enhancement: Added a new border to the text for readability.

- lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
Description
Steps to reproduce:
- Go to AddOrUpdateAlarmPage and then click Weather Condition Field a dialog box will come and in that there is some overflow towards right
Screenshots
Fixes https://github.com/CCExtractor/ultimate_alarm_clock/issues/464
> Fixed Weather Dialog Box Overflow issue

- lib/app/modules/timer/views/timer_view.dart
solve issue #486 
remove SizedBox and Use (main and cross) axisalignments for row and column
> fix the issue #486

- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner/Info.plist
- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
1. Notification Permissions functionality of permission_handler plugin was not setup properly, so it was not asking for permissions and directly causing an error, which results in not Navigating back to the home screen.
2. Both the systemAlertWindow & ignoreBatteryOptimization are Android only.
1. Updated info.plist for Notification permissions Group:
```
<key>PermissionGroupNotification</key>
<string>This app needs notification permissions to show notifications.</string>
```
2. Updated Podfile for asking Notification permissions using [these instruction](https://github.com/Baseflow/flutter-permission-handler/issues/1114#issuecomment-1649425295) given in one of the similar issues in the official github repo for permissions_handler plugin:
```
target.build_configurations.each do |config| …
```
> Fix: permissions related issues for both Platforms

- lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart
- lib/app/modules/alarmRing/views/alarm_ring_view.dart
Three increment snooze timer buttons added to snoozing view for user to modify snoozing duration.
P.S. Ignore the checks appearing due to the recording software.
> Feature: Add increment snooze timer buttons (Snooze window enhancement)

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
Introduced a new button to disable the challenge by setting isQrEnabled.value to false and qrValue.value to an empty string. Qr value can be only updated when user clicks on save button. Closing the dialog won't make any changes.
> feat: add disable qr challenge functionality

- lib/app/modules/home/views/home_view.dart
- lib/app/utils/language.dart
- lib/app/utils/languages/french_translations.dart
- lib/app/utils/languages/german_translations.dart
- lib/app/utils/languages/russian_translations.dart
- lib/app/utils/languages/spanish_translations.dart
The Ultimate Alarm Clock allows users to set, edit, and delete alarms seamlessly. Our enhancement adds a confirmation prompt to prevent accidental alarm removals.
When a user swipes to delete an alarm:
A confirmation message will appear, asking, “Are you sure you want to delete this alarm?”
Users can choose either “Yes” (to proceed with deletion) or “No” (to cancel).
https://github.com/CCExtractor/ultimate_alarm_clock/assets/143318563/3bf62cd7-b426-407a-acae-2e4a5ff293d6
> enhance swip- to-delete

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/example/ultimate_alarm_clock/MainActivity.kt
- android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerReceiver.kt
- lib/app/data/models/alarm_model.dart
- lib/app/data/models/alarm_model.g.dart
- lib/app/data/models/timer_model.dart
- lib/app/data/providers/isar_provider.dart
- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/addOrUpdateAlarm/views/choose_ringtone_tile.dart
- lib/app/modules/home/controllers/home_controller.dart
- lib/app/modules/home/views/home_view.dart
- lib/app/modules/splashScreen/bindings/splash_screen_binding.dart
- lib/app/modules/splashScreen/controllers/splash_screen_controller.dart
- lib/app/modules/splashScreen/views/splash_screen_view.dart
- lib/app/modules/timer/controllers/timer_controller.dart
- lib/app/modules/timerRing/bindings/timer_ring_binding.dart
- lib/app/modules/timerRing/controllers/timer_ring_controller.dart
- lib/app/utils/audio_utils.dart
- lib/app/utils/utils.dart
- lib/main.dart
Added a separate method channel for timer.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/cd0eda0c-a261-4d35-b4c7-ace6fab02fc7
> Added method channel

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
The content was flowing outside the box since there was no proper padding.
> fix: The description of the camera permission was going outside the box.

- lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart
- lib/app/modules/timer/views/timer_view.dart
make timer text field affect on number picker to solve the issue #516 
screen record : 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/86882938/2bf5c544-51d5-40eb-949a-f15bda0fd4b2
> make number picker affect timer text field, fix the issue #516

- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- pubspec.lock
Fixed an issue that was not allowing the user to Add an alarm just after adding an Alarm. 
Made changes to `lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart`.
> Add Update Button Fix. Issue #546

- .github/workflows/flutter.yml
- .gitignore
- android/app/build.gradle
- lib/app/data/providers/firestore_provider.dart
- lib/app/modules/about/views/about_view.dart
- lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/bottomNavigationBar/bindings/bottom_navigation_bar_binding.dart
- lib/app/utils/end_drawer.dart
- lib/app/utils/language.dart
- lib/app/utils/languages/french_translations.dart
- lib/app/utils/languages/german_translations.dart
- lib/app/utils/languages/russian_translations.dart
- lib/app/utils/languages/spanish_translations.dart
- linux/CMakeLists.txt
- pubspec.yaml
AddOrUpdateAlarmController was initialized on startup creating multiple bugs in the add alarm screen
Calling AddOrUpdateAlarmController inside the required function, instead of the onInit function of Input_time_controller
> Input time controller disposal fix

- android/app/build.gradle
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/GetLatestAlarm.kt
- android/build.gradle
gradle upgrade to 7.4.2 
gradle upgrade to 7.4.2 
> gradle upgrade 7.4.2

- .github/workflows/flutter.yml
- lib/main.dart
> github workflow java version bump to 17

- pubspec.lock
> flutter upgrade

- lib/app/modules/home/views/home_view.dart
- lib/app/modules/home/views/profile_config.dart
- lib/app/modules/settings/views/google_sign_in.dart
This PR resolves the overflow issue on different pages.
- Profile Config overflow
-  By setting a fixed width to parent widget containing text and adding `TextOverflow.ellipsis` in child text widget.
```dart
constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 2 / 3) 
```
```dart
overflow: TextOverflow.ellipsis 
```
- Delete Alarm overflow
- By giving a fixed width to the text widget and putting the alignment of *Toggle Button* and *Delete Icon* in proper way to match with the UI
- Setting Tile Overflow
- By removing the `SingleChildScrollView` widget from the parent widget which was taking infinite pixels. 
Before     | After      | Before     | After  
:-----------------------------------------------: | :----------------------------------------------: | …
> UI Overflow Issues Resolved

- lib/app/modules/timer/controllers/timer_controller.dart
- lib/app/modules/timer/views/timer_view.dart
- lib/app/utils/hover_preset_button.dart
- lib/app/utils/preset_button.dart
- pubspec.lock
This PR introduces the Preset Timers feature to the application. Users can now quickly set timers for predefined durations such as 1 Min, 5 Min, 10 Min, and 15 Min.
- The feature has been tested thoroughly in both Dark Mode and Light Mode, and it is functioning without any errors.
- The design and functionality ensure consistency across themes, providing a seamless user experience.
- Buttons for quick timer setup with predefined durations.
- Updated the timer view to include the preset buttons.
- Verified the functionality and appearance in both dark and light modes.
https://github.com/user-attachments/assets/c6d3c9ee-22c0-43d6-aef6-3985e153c48f
>  Added preset timers for easy accessibility

- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/modules/addOrUpdateAlarm/views/alarm_date_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/maths_challenge_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/note.dart
- lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/shared_alarm_tile.dart
- lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
- lib/app/modules/alarmChallenge/views/alarm_challenge_view.dart
- lib/app/modules/alarmChallenge/views/maths_challenge_view.dart
- lib/app/modules/alarmChallenge/views/pedometer_challenge_view.dart
- lib/app/modules/alarmChallenge/views/qr_challenge_view.dart
- lib/app/modules/alarmChallenge/views/shake_challenge_view.dart
- lib/app/modules/alarmRing/views/alarm_ring_view.dart
- lib/app/modules/splashScreen/views/splash_screen_view.dart
- lib/app/modules/stopwatch/views/stopwatch_view.dart
- lib/app/modules/timerRing/views/timer_ring_view.dart
- lib/app/utils/custom_error_screen.dart
I have added responsiveness wherever required by leveraging MediaQuery to adapt to different screen sizes effectively. For components that were already functioning well with Get.width and Get.height, I left them unchanged.
- Proposed to change the hardcoded height and width in the code base
> Add bug: added responsiveness where ever needed

- lib/app/modules/alarmChallenge/controllers/alarm_challenge_controller.dart
- lib/app/modules/alarmChallenge/views/maths_challenge_view.dart
- lib/app/modules/alarmRing/views/alarm_ring_view.dart
This PR fixes the behavior of the clear button in the math challenge screen. Previously, the button would clear the entire input, but now it removes digits one-by-one, matching user expectations.
alarm_challenge_controller.dart added removeDigit method
maths_challenge_view.dart updated onPressed
Replace 647  with the issue number which is fixed in this PR
https://github.com/user-attachments/assets/846d96ad-a3c2-4949-84e7-f77574c03b18
>  [Bug] Clear button deletes entire input in math challenge instead of removing digits one-by-one

- lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
- lib/app/utils/utils.dart
the bug is sloved 
updated the add_or_update_alarm_view.dart 
Replace `668` with the issue number which is fixed in this PR
https://github.com/user-attachments/assets/52242ef5-da14-413b-99aa-16d45d62621c
> Bug: AM and PM in the addOrUpdateAlarm the text is not fully completed

- .gitignore
- lib/app/data/providers/firestore_provider.dart
- lib/app/data/providers/isar_provider.dart
- lib/app/modules/about/bindings/about_binding.dart
- lib/app/modules/about/views/about_view.dart
- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/guardian_angel.dart
- lib/app/modules/addOrUpdateAlarm/views/qr_bar_code_tile.dart
- lib/app/modules/alarmChallenge/bindings/alarm_challenge_binding.dart
- lib/app/modules/bottomNavigationBar/bindings/bottom_navigation_bar_binding.dart
- lib/app/modules/home/bindings/home_binding.dart
- lib/app/modules/home/views/home_view.dart
- lib/app/modules/home/views/toggle_button.dart
- lib/app/modules/notifications/controllers/notifications_controller.dart
- lib/app/modules/settings/bindings/settings_binding.dart
- lib/app/modules/settings/controllers/settings_controller.dart
- lib/app/modules/settings/views/customize_undo_duration.dart
- lib/app/modules/settings/views/language_menu.dart
- lib/app/modules/settings/views/settings_view.dart
- lib/app/modules/timer/bindings/timer_binding.dart
- lib/app/modules/timer/views/timer_animation.dart
- lib/app/modules/timer/views/timer_view.dart
- lib/app/modules/timerRing/controllers/timer_ring_controller.dart
- lib/main.dart
Eliminate unnecessary imports to clean up the codebase and improve maintainability.
> Remove unused imports and dead code to improve code quality

- README.md
This PR updates the **Contribution Guidelines** to include a **Troubleshooting Environment Issues** section. New contributors have faced **Gradle build errors** and setup difficulties, so this documentation update provides clear steps to resolve them.  
- Added a **Troubleshooting Environment Issues** section.  
- Documented the **Gradle build failure** issue and provided a fix.  
- Included steps for **Flutter, Java, and Koala IDE setup** to ensure compatibility.  
- Linked the relevant **GitHub Issue** for further reference.  
Closes #702 
This update will help new contributors set up the project seamlessly, reducing onboarding issues.
> fixes #702: Update Contribution Guidelines with Troubleshooting Section

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
- lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
This PR fixes the text overflow issue in the `WeatherTile` widget. The issue occurred on small, medium, and large screens where the weather condition text would overflow and become unreadable and This PR removes the unnecessary request for location permission when selecting weather conditions for alarms. The weather condition feature does not require location data, and requesting location permissions can negatively impact the user experience.
- Wrapped the `Text` widget in the `trailing` property with `Flexible` to ensure it respects available space.
- Used `FittedBox` for the title to scale down the text if necessary.
- Added constraints to the `ListTile` to prevent overflow.
- Tested the changes on multiple devices to ensure responsiveness. …
> fix: resolve text overflow in WeatherTile for small, medium, and large screens

- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/AlarmReceiver.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/BootReceiver.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/GetLatestAlarm.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/LogDatabaseHelper.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/MainActivity.kt
- lib/app/data/providers/isar_provider.dart
- lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart
- lib/app/modules/debug/views/debug_screen.dart
- lib/app/modules/settings/views/settings_view.dart
- lib/app/utils/end_drawer.dart
- lib/main.dart
This PR implements several improvements to the alarm ringing functionality and adds a debug screen for better monitoring and troubleshooting. The changes focus on enhancing alarm reliability, improving logging, and providing better debugging capabilities.
1.MainActivity.kt
2.AlarmReceiver.kt
3.BootReceiver.kt
4.ScreenMonitorService.kt
5.LogDatabaseHepler.kt
1.Debug Screen 
2.Settings View
3.alar ring controller
4.isar_provider
https://github.com/user-attachments/assets/7ddd5c5a-cf04-4c14-815b-2e39b7a764a1
> Alarm Reliability Improvements and Debug Screen Implementation

- lib/app/modules/home/views/profile_config.dart
All the changes are done in the `profile_config.dart` file.
This PR makes the profile selection UI simple and intuitive.
After the changes...
https://github.com/user-attachments/assets/7d66e16a-9f8d-45c0-adf3-8d542f799722
And this is just a simple animation while opening the app(selected profile comes in view)
https://github.com/user-attachments/assets/daed9bfc-3e53-41d2-9336-630fc1a8195f
> Redesigned the Profile list-view UI

- lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart
This PR fixes the inconsistent UI of date picker while setting date on which alarm should ring.
Now the background of date picker is light colored in light mode and dark colored in  dark mode
Made changes in the datePicker() function in add_or_update_alarm_controller.dart for changing the background color of date picker according to the app theme.
**Date picker in Light mode**
**Date picker in Dark mode**
> Fixed alarm date picker UI

- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/AlarmReceiver.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/GetLatestAlarm.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/LogDatabaseHelper.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/Utilities/LocationFetcherService.kt
- android/app/src/main/kotlin/com/ccextractor/ultimate_alarm_clock/ultimate_alarm_clock/Utilities/WeatherFetcherService.kt
- lib/app/data/providers/isar_provider.dart
- lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart
- lib/app/modules/debug/controllers/debug_controller.dart
- lib/app/modules/debug/views/debug_view.dart
- lib/app/routes/app_pages.dart
This PR updates the LOG database schema to:
```
LogID INTEGER PRIMARY KEY AUTOINCREMENT,  
LogTime DATETIME NOT NULL,            
Status TEXT CHECK(Status IN ('ERROR', 'SUCCESS', 'WARNING')) NOT NULL,
LogType TEXT CHECK(LogType IN ('DEV', 'NORMAL')) NOT NULL,
Message TEXT NOT NULL,
HasRung INTEGER DEFAULT 0,
AlarmID TEXT
```
- Separated DEV logs and NORMAL logs
Also, the UI of the Debug Page is updated.
https://github.com/user-attachments/assets/52b6db7c-c652-433d-a037-b7e4208b518c
> Updated: log-database schema and UI of log page

- lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart
- lib/app/modules/alarmRing/views/alarm_ring_view.dart
- lib/app/modules/home/controllers/home_controller.dart
This PR resolves the issue that prevents the alarm from ringing when `Show Motivational Quote` is turned ON while setting an alarm.
Moved `showQuotePopup()` from **Home Controller** to **Alarm Ring Controller**
https://github.com/user-attachments/assets/f80757ff-bd3d-4d54-b567-215f453035ed
> fix: Alarm doesn't ring when `Show Motivational Quote` is turned on.

- lib/app/data/providers/firestore_provider.dart
- lib/app/data/providers/push_notifications.dart
There was a null check error in FirestoreDb.updateToken() when trying to access Firebase Auth user that wasn't logged in yet.
I fixed both FirestoreDb.updateToken() and PushNotifications.updateToken() methods to handle cases when the user isn't logged in.
> Firestore authcheck
