.vscode/settings.json, lib/app/modules/home/views/home_view.dart, pubspec.lock
I encountered a problem in the home_view.dart file, which resulted in a RenderFlex overflow issue. The issue occurred when the UI exceeded its available space, causing the layout to break.
To address the RenderFlex overflow issue, I made the following changes in the home_view.dart file:
1.Replaced the Container widget with the Card widget: The Card widget provides built-in padding and styling options, which helped to control the content within a defined boundary.
2.Added padding: By adding appropriate padding around the content, I ensured that the UI elements were properly spaced and didn't exceed the available space.
After implementing these changes, the RenderFlex overflow issue was resolved. The UI layout now behaves correctly, with no overflowing content.
=> Renderflex overflow issue

lib/app/modules/addOrUpdateAlarm/views/label_tile.dart, pubspec.lock
when user gives space it will ignore whitespace
some puspec.yaml files version got updated and the fix of wihtespace is in alarm tile is set when user will press space it automaticall ignore the space and accept it has some word
- [x ] Tests have been added or updated to cover the changes
- [ x] Code follows the established coding style guidelines
- [x ] All tests are passing
=> Fix: Alarm Tile will not allow take whitespaces  #65

lib/main.dart
I've restricted the landscape mode in this application. So if the user rotates the phone to any horizontal orientation, the app will not rotate and will stay in portrait mode. 
- I've used the SystemChrome services and added those in the `main.dart` file. 
_Please open the image for a better view._
<a href="https://ibb.co/ZMNFb3Z"><img src="https://i.ibb.co/ZMNFb3Z/Whats-App-Image-2023-09-24-at-6-21-13-PM.jpg" alt="Whats-App-Image-2023-09-24-at-6-21-13-PM" border="0"></a>
=> Feature: Restricted the Landscape Mode

lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart, lib/app/modules/settings/views/settings_view.dart
I'm showing a dialog when the user presses the back button on their device or app bar. This is implemented for a better user experience. If the user mistakenly presses the back button, it would have resulted in the loss of the data entered by the user in that particular alarm. But now, the user will be shown a dialog, and it will almost nullify the chances of such events. 
The structure of dialog looks like this:- 
```
Title: Discard Changes?
Message: You have unsaved changes. Are you sure you want to leave this page?
Actions: 
1. Cancel: It allows the user to stay on this page, and lets them edit their alarm. 
2. Leave: It lets the user confirm that they want to leave this page and discard any unsaved changes. 
```
- Introduced the `WillPopScope` widget as the root widget inside the …
=> Feature: Showing dialog when the user press back button on Add or Update Alarm View

lib/app/data/models/alarm_model.dart, lib/app/modules/home/controllers/home_controller.dart, lib/app/modules/home/views/home_view.dart, lib/app/modules/home/views/toggle_button.dart
This PR adds a new feature to the alarm app that allows users to select and delete multiple alarms simultaneously. Users can now long-press on any alarm to activate multi-select mode, and then choose one or more alarms for deletion.
- Added a long-press gesture detection to each alarm card.
- Implemented a multi-select mode that allows users to select and deselect alarms
- Added a new `AppBar` when user is in multi-select mode that allows user to 
- close the multi-select mode
- select all alarms at once
- delete alarms
- New toggle button in the alarm card when the user is in multi-select mode
- Animation when the user holds any alarm card
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/ad69a4c2-a543-4b93-baf4-d3c50e4ff3e9
=> Feature: Implemented Select Multiple Alarms to Delete on Holding an Alarm

lib/app/data/providers/secure_storage_provider.dart, lib/app/modules/settings/controllers/settings_controller.dart, lib/app/modules/settings/views/weather_api.dart
Currently, when users save or update their API Key in the app, the data is stored in local storage. However, if the app is hot-restarted, the apiKey TextEditingController is reset, causing users to lose their API Key text. This can lead to confusion and inconvenience for users. Because the API key is being saved in the local storage, they'll be unable to see it. 
To address this issue, I've implemented persistent storage for both the API Key and the Weather Key State. This enhancement will improve the user experience by preserving their API Key and the state of the Weather Key when the app is hot-restarted.
- Wrote new methods in the `secure_storage_provider` and the `settings_controller` for the addition and retrieval of the `WeatherKeyState`.
- When the `SettingsController` is invoked, …
=> Feature: Persistent Storage for API Key and Weather Key State

lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
Fixes #93
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/32d7b99f-6efc-465a-aac3-5c5014c46d2e
=> Label tile's snackbar bg color changed to red and text color changed to white

lib/app/utils/constants.dart
Previously, the `CheckBox fillColor` was looking weird for both light and dark modes. It was affecting the overall UX of the app. Therefore, I've changed the `CheckBox fillColor` for both light and dark modes. Now it's certainly looking better. 
- Changed the `CheckBox fillColor` to the primary background color of the respective light and dark modes.
**Before**
**After**
---
**Before**
**After**
=> Feature: Changed the checbox fill color

lib/app/modules/settings/views/weather_api.dart, lib/app/utils/constants.dart
Previously, when the user wanted to add/update their Weather API Key, they needed to tap on the Weather API key tile, and a dialog would appear there. However since the autofocus was off by default, the user needed to tap on the text field to enter their API Key.
In this PR, I've turned the autofocus on, so that user can now directly enter their API key. 
Also, I've provided a hint text `Enter API Key...` for a better user experience. 
- Turned the autofocus on inside the `TextField`.
- Provided a `hintText` inside the `TextField`.
- Changed the `hintStyle` inside the `InputDecorationTheme`.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/c6973031-68cb-4688-8ee7-b547245804d8
=> Feature: Turned autofocus on, and applied hint text to weather API textfield

lib/app/modules/alarmRing/views/alarm_ring_view.dart
Fixes #118 
Description:-
In the preview alarm, the Exit Preview button color and text Do not change according to the theme controller( error occurs when dark Mode is enabled).
How to Produce the issue:-
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/ac094151-2588-4acd-90fb-1a5ec2a65d25
After fixes:-
This issue mainly occurs when Dark mode is enabled.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/557cf961-e3df-4bdf-b25d-4e67aed45488
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/13bd94a4-06cd-4d37-9f39-0ce00868d928
=> Exit preview button (color and text) Now working properly according to whatever was defined in ThemeController

lib/app/modules/home/views/toggle_button.dart
Fixes #125 
Description:-
When we press&hold the alarm tile to delete it the toggle button's circular border color and animated circle color both are white which only goes with the Dark Mode Theme.
After fixing this issue:-
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/7e44ed39-dd9e-41f7-a042-f34089124eb6
=> Fixes: Toggle button's circular border color and animated circle color in Light Mode theme.

lib/app/data/models/ringtone_model.dart, lib/app/data/models/ringtone_model.g.dart, lib/app/data/providers/isar_provider.dart, lib/app/data/providers/secure_storage_provider.dart, lib/app/modules/alarmChallenge/controllers/alarm_challenge_controller.dart, lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/settings/controllers/settings_controller.dart, lib/app/modules/settings/views/custom_ringtone.dart, lib/app/modules/settings/views/settings_view.dart, lib/app/utils/constants.dart, lib/app/utils/utils.dart, pubspec.yaml
I've implemented the custom ringtone feature. So now the users will have a choice between playing the default alarm ringtone, or their chosen ringtone. 
I've used the `file_picker` dependency for picking the audio file from the user's device. To store the ringtone data locally, I've implemented the `RingtoneModel`, and saved it to the ISAR database. To play the chosen ringtone, I've used the `audioplayers` dependency as we can't play the audio file in the form of bytes in the `flutter_ringtone_player` dependency.
- Added `file_picker` and `audioplayers` dependency.
- Added Custom Ringtone tile in Settings View.
- Added an enum and outlined button theme to constants file.
- Added methods for playing and stopping the alarm to Utils class.
- Added methods for saving, retrieving, and deleting …
=> Feature: Implemented Custom Ringtone Feature

lib/app/modules/home/views/home_view.dart
Overflowing of the top navigation bar while selecting multiple alarms for deletion in the home screen has been fixed.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/94671974/15daea17-84ce-426b-af9e-de63dd9778db
=> Add fix: Select all Top navigation bar corrected

lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart, lib/app/modules/alarmRing/views/alarm_ring_view.dart
In the newer versions of the Flutter, the `WillPopScope` widget is deprecated. So I've replaced it with the newly included `PopScope` widget. 
- Replaced the `WillPopScope` widget with the `PopScope` widget. 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/79699520-e56b-4410-8ebf-bdadfaaa70b9
=> Deprecation: Replaced the Deprecated WillPopScope with PopScope

lib/app/utils/constants.dart
I've set the `useMaterial3` property in the dark and light `ThemeData` to `false`. It was impacting the overall theme of our application. 
- Set the `useMaterial3` property to `false` in `ThemeData`.
=> UI Fix: Disabled the material3 theme

.github/ISSUE_TEMPLATE/bug.yaml
Previously, when the contributor tried to create an issue of type bug, the title "Bug: " wasn't there. So I've added the title "Bug: " to the bug issue template.
- Added the title "Bug: " to the bug issue template.
=> Bug: Added the bug title to the bug issue template

lib/app/modules/settings/views/custom_ringtone.dart
Previously when the user had enabled the custom ringtone feature and didn't select any audio file, the dialog would still get dismissed. But I've added the `barrierDismissable` condition, and `onWillPop` method inside the dialog now. So the user will only be able to dismiss the dialog either if they have disabled the feature or enabled the feature and selected a ringtone. 
- Added the `barrierDismissable` condition.
- Added the `onWillPop` method.
- Added the `disabledBackgroundColor`. 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/416b32e8-e540-4d00-b363-dd60b36b0464
=> Bug: Resolved the no ringtone selected bug

lib/app/modules/about/controller/about_controller.dart, lib/app/modules/about/views/about_view.dart
Since the `canLaunch` and `launch` methods in the `url_launcher` were deprecated, I've replaced them with the `canLaunchUrlString` and `launchUrlString` methods.
- Replaced the `canLaunch` and `launch` methods with `canLaunchUrlString` and `launchUrlString` respectively.
- Formatted the `about_view.dart` file.
=> Deprecation: Replaced the deprecated methods of url_launcher

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, pubspec.yaml
Previously, when the user used to create or update an alarm, the app didn't show any confirmation event about it. 
In this PR, I've added the [fluttertoast](https://pub.dev/packages/fluttertoast) dependency to the project and used it to show a toast whenever the user sets/updates an alarm. 
The message of the toast is the difference between the current time and the alarm time. 
_Note: `Get.snackbar` isn't used as a toast because it requires you to provide the title and message. Also if you provide an empty string as a title, the height of the snack bar can't be reduced._
- Added the `fluttertoast`dependency.
- Showing the toast whenever the user sets/updates an alarm. 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/e0e72c66-23a5-4600-af61-ebf6cef95956
=> Feature: Showing flutter toast on creating or updating the alarm

android/app/src/main/kotlin/com/example/ultimate_alarm_clock/MainActivity.kt, lib/app/utils/utils.dart, pubspec.yaml
Previously, the app was using the `flutter_ringtone_player` package for playing the device's default alarm ringtone. But the `audioplayers` package is also being utilized in the `Custom Ringtone` feature. 
But obviously, it's not feasible to have two packages contributing to just a ringtone-playing feature, and especially to have the `flutter_ringtone_player` package just to play the device's default alarm ringtone. 
So I've removed the app's dependency on the `flutter_ringtone_player` package by using the `MethodChannel` and invoking the native methods for playing and stopping the device's default alarm ringtone. 
I've written two methods named `playDefaultAlarm`, and `stopDefaultAlarm` for playing and stopping the alarm ringtone respectively. 
- Removed the `flutter_ringtone_player` …
=> Refactor: Removed the app's dependency on flutter_ringtone_player

android/app/src/main/AndroidManifest.xml, lib/app/data/models/ringtone_model.dart, lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/choose_ringtone_tile.dart, lib/app/modules/alarmChallenge/controllers/alarm_challenge_controller.dart, lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/home/views/home_view.dart, lib/app/utils/audio_utils.dart, lib/app/utils/utils.dart, lib/main.dart, pubspec.yaml
This PR addresses the issue where background music playing on the device is not paused when the alarm rings, leading to a poor user experience. 
The solution involves using the [audio_session](https://pub.dev/packages/audio_session) package to handle interruptions and ensure a smoother transition between the alarm ringtone and background music.
- Implemented audio session configuration using the `audio_session` package to manage interruptions during alarm ringing.
- Set up the global context of the audio player for consistent and coordinated playback control.
- Introduced a new file, `audio_utils.dart`, to centralize audio utility functions for better organization and maintainability.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/d1a63223-a546-4ee5-bda5-340e97683070 …
=> Bug: Handle background audio interruptions when alarm rings

lib/app/modules/alarmRing/views/alarm_ring_view.dart
When we click "preview alarm," the snooze button shows beneath the dismiss button.
Padding added to snooze button in preview alarm.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/a6404327-f4d2-4557-b335-bcf468b4567f
=> Padding added to snooze button in preview alarm.

lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart, lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
When we manually enter the time in a text field and want to complete the task, we have two options. Firstly, we can click anywhere on the screen to exit the text field. Secondly, we can click on the "done" button located on the soft keyboard.
To improve the app's user experience, I suggest adding a dedicated "Tick" or "Done" button. This button should only be visible when the user clicks on the timePickerSpinner to enter the time manually. This will make it more convenient for the user to confirm their selection and provide a better overall experience.
Done Button added in the "add_Or_Update_alarm" in timePickerSpinner when entering the time manually.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/88525320/136f1b77-19bd-47d2-be09-b4db33cfb72d
=> Done Button added in the "add_Or_Update_alarm" in timePickerSpinner when enter the time manually.

lib/app/modules/home/views/home_view.dart, pubspec.yaml
In home_view.dart in the DrawerHeader the row was overflowing on some devices due to it being static and not adjusting by the flex property.
1) Added the flex property to the widget so that they never overflow using the Flexible widget,
2) Also replaced the sizedBox with Gap() which required an import and an extra package in pubspec.yaml
just because Gap works better in flexible containers and will give less issues in future versions aswell.
=> Fixed #275 on Render overflow in home_view.dart drawer

lib/app/modules/settings/views/google_sign_in.dart, lib/app/modules/settings/views/weather_api.dart
fixes #251 
- unnecessary ripple removed from settings includes buttons like 
- Open Weather map api
- sign- in with google
**Have a look**
https://github.com/CCExtractor/ultimate_alarm_clock/assets/103873587/dd6e2353-36b0-43c8-9805-811dfe508b25
=> Unnecessary ripple removed from settings

lib/app/modules/settings/views/language_menu.dart
fixed background and text colour of select language menu list according to theme.
In dark mode list should be in dark theme and in light mode should be light theme
=> fix: dropdown theme

lib/app/modules/home/views/home_view.dart
When you choose Russian then the russian conversion of message 'No upcoming alarms!' got overflows
I have removed right padding of container and currently only left side has padding of 25 which was initially defined, if you allow me to decrease left padding to 20 then it would be safer.
=> fix: appBar pixel overflow in Russian language

lib/app/modules/home/controllers/home_controller.dart, lib/app/modules/home/views/home_view.dart
When users swipe to delete an alarm, the application temporarily stores the deleted alarm model in a variable, displaying a Snackbar with an "Undo" option. The Snackbar is powered by ScaffoldMessenger showSnackBar and has a duration of 4 seconds, allowing users to easily undo the deletion within that timeframe
1. Used ScaffoldMessenger method showSnackBar to create a Snackbar for displaying the "Undo" feature.
2. Design the Snackbar to include an "Undo" button, providing users with an option to reverse the deletion.
3. When the user taps "Undo" within the Snackbar, restore the previously deleted alarm model back to the database.
4. Set the duration of the Snackbar to 4 seconds, providing users with a reasonable timeframe to decide whether to undo the deletion.
5. Optimize the visual …
=> Undo added on swipe to delete alarm using ScaffoldMessenger

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/repeat_once_tile.dart, lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart, pubspec.lock, pubspec.yaml
- Changed the Repeat once tile's name to `Ring once`
- Added 2 more options to select days easily:
- Daily
- Weekends
=> Add options to select days while adding/updating an alarm

lib/app/modules/timer/views/timer_view.dart
The issue was to change the settings icon to an endDrawer so that the UI stays the same in both the changes.
Issue `#307` Replacing settings icon in the timer section to menu icon
=> Feature: Replacing settings icon in the timer section to menu icon

lib/app/modules/bottomNavigationBar/views/bottom_navigation_bar_view.dart, lib/app/modules/home/views/home_view.dart, lib/app/modules/timer/views/timer_view.dart, lib/app/routes/app_pages.dart
Our app only had the option to use bottomNavigationButton to switch pages. Now, we can simply swipe pages to go to the next one. On top of that, I have limited the deletion to only left to right so that if the page is filled with alarms, the user doesn't accidentally delete it.
I have also added a red animation on the dismiss of the tile to delete.
Fixes Issue #308 Feature: Adding swipeable view
https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/a3b4dc67-3512-474c-b422-89d48639b76b
=> Feature: Swipe Pages and Animation Effect on deletion

lib/app/modules/home/controllers/home_controller.dart
When swiping to delete multiple alarms simultaneously, the application does not remove the previous "Undo" option before displaying the new one. This behavior can lead to confusion as users may unintentionally trigger the wrong undo action.
Added a check to clear the current Snackbar if it is open before displaying a new one
=> Remove the previous "Undo" option before displaying the new one

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/choose_ringtone_tile.dart
- Wrapped scrollbar widget with card which doesn't allow the element of scrollbar widget to flow outside.
- Added divider between two list which is giving list effect.
- Make scroll bar always visible.
- Some changes in snackbar which appears after modification in list(like added margin, duration, position, colour and blur amount).
https://github.com/CCExtractor/ultimate_alarm_clock/assets/78961406/04b0ad30-a2dc-484f-981d-b72d76ac38d1
=> fix selected ringtone is visible outside the container

lib/app/modules/home/views/home_view.dart
Previously when the user deletes an alarm via swipe or pop-up menu button, the behavior seemed inconsistent as the snack bar was not being shown on alarm deletion via pop-up menu. 
So I have made changes to display the snack bar on alarm deletion via the pop-up menu button. 
- Display `Get.snackbar` when the user deletes an alarm via the pop-up menu.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/7d61b6a7-b9e0-4da8-a004-ff9c7f4f1185
=> Feature: Displayed snack bar on alarm deletion via pop-up menu

lib/app/modules/home/views/home_view.dart, lib/app/modules/timer/views/timer_view.dart
Resolved UI mismatch by integrating the alarm screen's end drawer into the timer screen .
Introduce consistency in the UI by aligning the end drawer of the timer screen with the one present in the alarm screen. This enhancement ensures a unified and cohesive user experience across both features.
=> End Drawer: Resolved End Drawer mismatch of ui in Alarm and timer screen 

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/choose_ringtone_tile.dart
Previously, the application faced issues with inaccurate ringtone counter values, resulting in the failure to delete custom ringtones under certain conditions.
A new variable has been introduced to track the previously selected ringtone. When some other ringtone is selected, its counter is incremented while the counter for the previously selected ringtone is decremented.
Before fix:
https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/c85b0c98-de7b-4b84-8143-e6616cefc05e
After fix:
https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/c52ebc3b-ba56-4938-aa5d-951f1ace5c01
=> [Ringtone counter fixed] issue #262

lib/app/modules/settings/controllers/settings_controller.dart, lib/app/modules/settings/views/weather_api.dart
Currently, the API Key dialog displays an error text even after the user closes and reopens the dialog. This PR addresses the issue by ensuring that the error text is not shown once the dialog is closed.
- Resolved the issue of error text persisting in the API Key dialog.
- Renamed the `validate` variable to `isApiKeyEmpty` for improved clarity.
- Added missing required trailing commas in the `SettingsController` and `weather_api.dart`. 
- Formatted the `SettingsController` and `weather_api.dart` files for consistency.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/39df6ca7-6990-4067-97bc-3ca2c3cfa0d7
=> Bug: Resolved Error Text Persisting in API Dialog

lib/app/modules/stopwatch/views/stopwatch_view.dart, lib/app/modules/timer/views/timer_view.dart
When the font size on the mobile device is increased, the stopwatch UI within the alarm app becomes partially hidden.
Using Expanded instead of sizebox
Before:
After:
=> zoomed stopwatch and timer UI fixed

lib/app/modules/bottomNavigationBar/views/bottom_navigation_bar_view.dart
We can add a timelapse icon to look like the 'time is running out' icon, which is the point of the timer.
=> styling: Timer icon

android/app/google-services.json, lib/app/modules/home/controllers/home_controller.dart, lib/app/modules/home/views/home_view.dart
Expected behaviour
1. If an alarm is scheduled, show the remaining time until it rings.
2. If no alarm is set, display the message "No alarm scheduled" instead of a misleading countdown.
Actual behaviour
1. If an alarm was scheduled, the remaining time until it rang was displayed.
2. If the alarm is turned off, after a few seconds, it will show the remaining time until it rings if it was turned on.
`await Future.delayed(delay);` caused alarms to still notify even after being turned off. To fix this, I swapped the `Future` for a regular `Timer`. Now, when an alarm's state changes, the timer is cancelled immediately, ensuring "Next alarm" accurately reflects the alarm's true status.
=> fix: Display 'No Alarm Scheduled' Message When No Alarm is Set

lib/app/modules/stopwatch/controllers/stopwatch_controller.dart
I've made a small fix to the stopwatch functionality. Previously, there was an issue where the milliseconds part of the stopwatch would reset when pausing and resuming it. I've addressed this issue by updating how the milliseconds are calculated.
**before fix:**
https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/9d6c6234-ac59-4199-ab80-b103d5f37315
**after fix:**
https://github.com/CCExtractor/ultimate_alarm_clock/assets/144731286/9a3f397a-9572-4bdf-9951-9c5d28a8831b
=> Fixed stopwatch milliseconds reset issue

lib/app/modules/home/views/home_view.dart
"Hold Gesture" for bulk deleting alarms and the "Swipe to Delete" functionality can run simultaneously
When attempting to use the "Hold Gesture" to initiate bulk deletion of alarms, the "Swipe to Delete" functionality can be triggered simultaneously. This behavior is inconsistent with the intended functionality, as the "Hold Gesture" should exclusively activate the bulk delete feature without interference from other gestures.
conditionally setting the direction property of the Dismissible widget based on the value of the isAnyAlarmHolded controller 
https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/2e9cceed-2b71-4386-b514-497a9de69ad1
=> fix: onholdtodelete and swipetodelete will not run at same time

ios/Flutter/AppFrameworkInfo.plist, ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
I've resolved the installation issue on iOS by addressing the version incompatibility between the Podfile and Podfile.lock. As a result, the app now installs successfully on iOS device.
I updated the Podfile.lock to match the dependencies in the repository and defined a global platform in the Podfile based on the minimum platform version requirement for each dependency in the repo.
Here's the screenshot of app successfully getting installed on iOS device after this fix.
=> fix: iOS podfile and podfile.lock version compatibility issue

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
This pull request addresses several bugs related to the `RepeatTile` in the `AddOrUpdateAlarmView`:
- Daily list tile's checkbox is not responsive.
- Weekdays checkbox functionality inconsistency.
- Custom list tile checkbox remains selected even with no days selected.
- Custom list tile checkbox doesn't trigger day selection dialog.
- Toggling Custom list tile checkbox is broken after selection.
- **Daily Tile**: Investigated and fixed the cause of the unresponsive checkbox behavior.
- **Weekday Tile**:
- Added `handleWeekdayTileTap` to accurately reflect selected days in the tile text when tapped.
- Ensured consistency between checkbox selection and tile text display.
- **Custom Tile**:
- Implemented `checkIfAnyDaySelectedInCustomTile` to accurately determine if any custom days are …
=> Bug: Resolved the Repeat Tile Bugs

lib/app/modules/settings/views/weather_api.dart
Currently, the `Weather API Key Dialog` doesn't display an error message when the user enters only whitespaces in the API key field. This pull request addresses this issue by ensuring the error message is shown both for empty entries and entries containing only whitespace characters.
- Instead of directly evaluating the text field's text property for emptiness, trim leading and trailing whitespaces first, and then check.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/5f99cc04-cf18-4d90-9315-ff78ae6434a2
=> Bug: Resolved Error Text Not Shown On Entering Whitespace

lib/app/modules/home/controllers/home_controller.dart, lib/app/modules/settings/controllers/settings_controller.dart, lib/app/modules/settings/views/customize_undo_duration.dart, lib/app/modules/settings/views/settings_view.dart
Undo Duration allows users to customize the duration of the undo option. By default, the undo duration is set to 4 seconds, but with this new feature, users have the flexibility to adjust it according to their preferences.
The "Undo Duration" setting allows users to tailor the time window for undoing actions. By default, the duration is set to 4 seconds, striking a balance for typical use cases. Users seeking a personalized experience can easily adjust the undo duration to better suit their workflow.
Flexibility: Users can adapt the undo duration to match the pace and complexity of their tasks.
Efficiency: Tailoring the undo duration enhances productivity for various use cases.
User-Centric: Providing customization options contributes to a user-friendly experience.
Replace `issue_no` with …
=> Customise undo duration

lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart, lib/app/modules/bottomNavigationBar/bindings/bottom_navigation_bar_binding.dart, lib/app/modules/timer/bindings/timer_binding.dart, lib/app/modules/timer/views/timer_view.dart
Currently, the app only offers the `TimePickerSpinner` for setting timer duration. This pull request introduces manual time entry functionality to enhance user experience and provide an alternative input method.
- **Manual Time Entry:**
- Implemented `InkWell` to switch between TimePickerSpinner and manual input.
- Implemented text fields for individual input of hours, minutes, and seconds.
- Validated user input to ensure valid time values (0-23 hours, 0-59 minutes, 0-59 seconds).
- Updated timer duration based on user-entered values.
- I have implemented the required methods and properties in the `InputTimeController`, similar to the approach used in `AddOrUpdateAlarmView`.
https://github.com/CCExtractor/ultimate_alarm_clock/assets/92971894/be1386a6-4be2-493c-b40c-5a15d9cae66c
=> Feature: Added Manual Time Entry Option in Timer

android/app/google-services.json, lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart, pubspec.lock, pubspec.yaml
When I enter an alarm tile and attempt to exit it, a dialog box appears even if no changes were made. This behaviour should be adjusted to only display a pop-up message if changes were made but not saved or updated.
Created a map to store initial values and changed values. I added listeners to the required variables and compared the initial value and current value, storing them in the changed values map. In PopScope, check if the user has unsaved changes and pop the page.
=> fix: track unsaved changes on add-or-update-alarm-view

lib/app/modules/bottomNavigationBar/controllers/bottom_navigation_bar_controller.dart, lib/app/modules/bottomNavigationBar/views/bottom_navigation_bar_view.dart, lib/app/modules/home/views/home_view.dart
Introduces a `hasLoaded` variable in the bottombarcontroller to ensure the pageView is only loaded after the await method `_loadSavedState` returns
also removes the animation for navigating from 1 page to another
https://github.com/CCExtractor/ultimate_alarm_clock/assets/72601105/b2bcfe69-903e-453b-b64b-d95a19720c0f
=> Fixes PageState not loading using the correct index after closing the app.

lib/app/modules/addOrUpdateAlarm/views/shared_alarm_tile.dart
solve over flow error in enable shared alarm in settings for every alarm ,using expanded widget instead of Sized box that defines fixed size.
=> solve over flow error in enable shared alarm dialog

.gitignore, README.md, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/AlarmReceiver.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/BootReceiver.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/DatabaseHelper.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/GetLatestAlarm.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/MainActivity.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerReceiver.kt, lib/app/data/models/alarm_model.dart, lib/app/data/providers/firestore_provider.dart, lib/app/data/providers/isar_provider.dart, lib/app/modules/splashScreen/controllers/splash_screen_controller.dart, pubspec.lock, pubspec.yaml
SQLite databases offer the advantage of being easily accessible across various native languages, thereby facilitating a smooth exchange of data. I have implemented the SQLite database using sqflite package in Flutter and using the database created directly in Kotlin code for scheduling alarms on boot in the background.
Addition of SQLite database which stores all alarm data for easy access
New boot scheduling for alarms
=> Database cross comm

android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/BootReceiver.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/CommonTimerManager.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/GetLatestAlarm.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/MainActivity.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerBroadcasts/CancelTimer.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerDatabaseHelper.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerFunctions.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerNotification.kt, android/app/src/main/kotlin/com/example/ultimate_alarm_clock/TimerService.kt, lib/app/data/models/timer_model.dart, lib/app/data/models/timer_model.g.dart, lib/app/data/providers/isar_provider.dart, lib/app/modules/bottomNavigationBar/controllers/bottom_navigation_bar_controller.dart, lib/app/modules/home/controllers/home_controller.dart, lib/app/modules/timer/controllers/timer_controller.dart, lib/app/modules/timer/views/timer_animation.dart, lib/app/modules/timer/views/timer_view.dart, lib/app/modules/timerRing/controllers/timer_ring_controller.dart, lib/app/utils/utils.dart, lib/main.dart, pubspec.lock
Multiple timer support
Easy to use UI
Timer in Notifications when app is minimized
direct Kotlin database access for snappier performance with no need to call flutter for data.
=> Timer revamp

lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
This overflow occurs on small screens only.
This is resolved by:
- Wrapping repeat tile contents in `SingleChildScrollView` and putting `mainAxisSize: MainAxisSize.min` in its child i.e. Column.
Small Screen Devices   |     Normal Devices
------------------------------- | ------------------------------
<video src="https://github.com/user-attachments/assets/e57ee551-7bd3-4c52-9f72-d7e3a890c07d" width=50%> | <img src="https://github.com/user-attachments/assets/28d75463-8e45-4c6c-bddb-dcf9b2cd093a" width=60%>
=> Bottom Overflow in Repeat Tile UI on Small Screen Devices

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/maths_challenge_tile.dart
This overflow issue was due to `NumberPicker` widget, when the `min` and `value` arguments of this widget were 1 or greater, then it shows this overflow error.
How I resolved?
- I changed the `min` and default value of `numMathsQuestions` as `0` and `0.obs`, respectively.
- Then, in `Save` button of dialog, it will check for condition, that for setting `controller.isMathsEnabled.value` to `true` the number of questions should be greater than 0. 
- Else, it will remain `false` by default and Maths Challenge will not be enabled until you select number questions to be greater than 0.
=> Add fix #606: Overflow Issue Resolved 

lib/app/utils/constants.dart, pubspec.lock, pubspec.yaml
- Toggle Switch Visibility in Light Mode
- The switch.dart file has been updated to ensure that toggle switches are clearly visible when       the app is in light mode.
- Updated the code in switch.dart to enhance toggle switch visibility in light mode.
Fixes #612
[ ] Tests have been added or updated to cover the changes.
[ ] Documentation has been updated to reflect the changes.
[ ] Code follows the established coding style guidelines.
[ ] All tests are passing.
=> Fix Toggle Switch Visibility in Light Mode

lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
This PR addresses the fix for issue #638 where the "Save" button on the AddOrUpdateAlarmView screen would overlap the content during scrolling. The changes ensure that the button remains fixed in its intended position, with only the screen content above it being scrollable.
- Changed the body to Column widget with scrollable part inside the SingleChildScrollView with the help of Expanded widget and the save button outside the scrollable part.
- Verified that the scrolling behavior works correctly without impacting the button's functionality or position.
- [☑️] Tests have been added or updated to cover the changes
- [☑️] Documentation has been updated to reflect the changes
- [☑️] Code follows the established coding style guidelines
- [☑️] All tests are passing
=> Fix: Issue #638, save button initially over text now as a separate button below the add/update alarm form.

lib/app/modules/addOrUpdateAlarm/views/shake_to_dismiss_tile.dart, lib/app/modules/addOrUpdateAlarm/views/snooze_duration_tile.dart
Snooze Tile Bottom Overflow & NumberPicker Error Fix: wrapped Column widget in a sized box to prevent overflow, then handled 0 or negative values for snooze duration to fix number picker error
This pull request resolves two primary issues in the Snooze Tile dialog:  
1. **Bottom Overflow:** The `Column` widget causing layout overflow has been wrapped in a `SizedBox` with a defined height to prevent the issue.  
2. **NumberPicker Error:** The `NumberPicker` was not properly handling zero or negative values. This is fixed by clamping the minimum value to `1` in the widget logic.
- Wrapped the `Column` widget in a `SizedBox` to prevent overflow. 
- Updated `NumberPicker` logic to ensure `controller.snoozeDuration.value` is at least `1` to avoid invalid values.
` value: …
=> Snooze Tile Bottom Overflow & NumberPicker Error Fix

lib/app/modules/timer/views/timer_animation.dart
This pull request fixes the "bottom overflowed" issue in the TimerAnimatedCard component of the Flutter timer application by adjusting the height of the container.
Changed the height calculation of the container in the TimerAnimatedCard widget from context.height / 3.3 to context.height / 3.0.
=> Fix: changed the height of container from 3.3 to 3.0

lib/app/data/models/flag_model.dart, lib/app/modules/stopwatch/controllers/stopwatch_controller.dart, lib/app/modules/stopwatch/views/stopwatch_view.dart
Added flags to stopwatch. Now users can add laps and see flags in stopwatch.
Attached screenshots and video.
[Video link](https://github.com/user-attachments/assets/1c1c62fe-7543-41db-b087-11725303b0a3)
=> Feature: flags added to stopwatch

lib/app/modules/alarmRing/views/alarm_ring_view.dart
Changes Introduced
This PR adds an Exit Preview button to the Alarm Control Screen. The button allows users to exit the alarm preview and return to the main screen (/bottom-navigation-bar) without dismissing the alarm.
Key Changes
Added a new Exit Preview button at the bottom of the Alarm Control Screen.
The button has a red background with white text for visual distinction.
It triggers haptic feedback when pressed.
It navigates the user back to the main screen without dismissing the alarm.
Added a gap between the Dismiss button and the Exit Preview button for better visual separation.
Ensured the Dismiss button retains its original styling and functionality.
https://github.com/user-attachments/assets/981d71f8-caaf-44d6-b365-f4c2d1316d17
Replace 640  with the issue number which is fixed …
=> feat: Add Exit Preview button to Alarm Control Screen

lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
- When creating a new alarm and setting the repeat to `Weekdays`, it incorrectly selects 'Tue, Wed, Thu, Fri & Sat'
- In the same section the repeat to `Daily` checkbox was not doing anything when clicked.
fixes #678 
fixes #679 
https://github.com/user-attachments/assets/ff002b19-daaa-42c7-853f-93af0113518b
=> fix: incorrect weekdays & 'Daily' checkbox in `repeat_tile` widget

lib/app/utils/preset_button.dart
This PR addresses the fix for issue #652 where the text used as a preset for starting a new timer (+1:00, +5:00 etc.) were being cropped off from bottom in some devices due to a different attribute (fixedSize) used in Elevated button's style causing this issue.
- Changed the 'fixedSize' attribute which used the Size() property to define the button to 'minimumSize'.
- This new attribute makes sure the button's size adjusts to a minimum size so it does not get cropped by the screen dimensions and the widget dynamically takes up its space.
- Tested the changes on virtual and physical devices.
- [☑️] Tests have been added or updated to cover the changes
- [☑️] Documentation has been updated to reflect the changes
- [☑️] Code follows the established coding style guidelines
- [☑️] All tests are …
=> Fixed issue #652,Timer start preset text cropping solved.

lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart, lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
This PR adds an automatic AM/PM toggle feature when the user sets the time to 12:00. The changes include:
- Added logic to toggle AM/PM in the `NumberPicker` when the time is 12:00.
- Added logic to toggle AM/PM in the `TextField` when the time is 12:00.
- Ensured compatibility with both 12-hour and 24-hour formats.
updated the input_time_controller.dart with some logic
updated the add_or_update_alarm_view.dart
https://github.com/user-attachments/assets/c526fea4-679f-411b-ba6e-47fd000388f1
=> PR: Fix AM/PM Toggle on Boundary Transition in InputTimeController

lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/alarmRing/views/alarm_ring_view.dart
This PR fixes an issue where the alarm ringing screen always displayed the time in 12-hour format, even when the 24-hour format was selected in the settings. The time now properly reflects the user’s chosen format.
- Used SettingsController to check if 24-hour format is enabled.
- Updated AlarmControlView to display controller.timeNow24Hr when 24-hour format is selected.
https://github.com/user-attachments/assets/10cd84b2-2b03-4c98-8473-bb18c9a58a55
**the red color is only used for testing purpose!**
=> Fix: Alarm displays incorrect time format while ringing

lib/app/modules/addOrUpdateAlarm/views/screen_activity_tile.dart
This PR resolves an issue where the screen activity toggle button does not update its reactive state properly in the dialog. When the dialog is opened, the initial state is stored, but toggling the switch does not explicitly update the observable variable (`controller.useScreenActivity`), which leads to inconsistencies between the dialog toggle and the main list tile toggle.
- Updated the `onChanged` callback inside the dialog’s switch within `ScreenActivityTile` to explicitly update `controller.useScreenActivity`.
- Ensured that the reactive variable is updated immediately, and the associated activity monitor state (`controller.isActivityMonitorenabled`) is properly set.
- Verified that toggling the switch in the dialog now reflects accurately in both the dialog and the main view. …
=> Fix Screen Activity Toggle Button State Issue in ScreenActivityTile

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/location_activity_tile.dart, lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
This PR solves the following issues while adding/updating an alarm:
- When selecting `Weather Condition`, the app first finds the location and then opens the popup. Since retrieving location can take some time, the app seems to be stuck, and the popup does not appear. (There is no need for getting the location at this point; location is only needed when the alarm is about to ring.)
- When selecting `Location Based`, the same happens; the app first retrieves the location and then open the popup.
After the changes, when selecting;
- `Weather Condition`: There is a check for location access only.
- `Location Based`: The popup opens, then the location is retrieved.
These changes just make the app more responsive and fast.
fixes #699 …
=> Fix: Updated `weather_tile` and `location_activity_tile`

lib/app/modules/home/views/profile_config.dart
This PR fixes the issue where weather selection in the Profile section was not updating after closing the dialog. The issue was caused because profileModel was not passed as an argument when navigating to /add-update-alarm, leading to an incomplete state update.
- Passed profileModel as an argument in Get.toNamed('/add-update-alarm').
- Ensured weatherTypes correctly updates from profileModel.value.weatherTypes.
- UI now reflects selected weather types after closing the dialog.
=> Changes Made : UI updates after selecting weather in the profile section

lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
The clock hands used to set an alarm display the time incorrectly when the hour format has been changed from 12-hour format to 24-hour format or vice-versa. When opening the new alarm screen after changing time format settings, the clock hands continue to display time in the previous format.
The issue occurs in the onChanged handler for the hours NumberPicker in the add_or_update_alarm_view.dart file. The current implementation always uses the inputTimeController.convert24() method to convert the time, regardless of whether the app is in 24-hour mode or 12-hour mode. This causes incorrect time conversion when switching between formats.
1. Modified the onChanged handler for the hours NumberPicker to properly handle time format changes.
2. Added conditional logic to handle hour values …
=> fix: #504 Erratic time display after changing hour format.

lib/app/modules/addOrUpdateAlarm/views/guardian_angel.dart
This PR fixes a bug where the Guardian Angle feature could be enabled without entering a phone number. The fix adds proper validation to ensure the feature is only enabled when a valid phone number is provided.
1. Added validation in the Guardian Angle dialog's Submit button
2. Added error feedback using snackbar when no phone number is entered
3. Ensures the guardian phone number is properly set before enabling the feature
https://github.com/user-attachments/assets/075f06a4-f204-44fb-bbda-d7335bf84ded
=> Fix: Guardian Angle Feature Validation

lib/app/modules/addOrUpdateAlarm/views/snooze_duration_tile.dart
Solved the malfunction of scroll view while setting snooze duration feature for an alarm 
Also changed the max possible snooze duration from 1440 minutes to 60 minutes which seems much more sensible.
https://github.com/user-attachments/assets/ed6549d4-e5c0-4931-9e97-95bae6a02832
=> Fix: Snooze duration scroll issue solved

lib/app/modules/timer/views/timer_view.dart
The hover buttons on the Timer tab shifts its layout when switched to keyboard type Input
- Fixed the position of the buttons from Top by 60.
- works for all screens
- removed extra code used previously
=> fix: Layout shift of timer hover buttons

lib/app/modules/home/controllers/home_controller.dart, lib/app/modules/home/views/home_view.dart, lib/app/modules/home/views/toggle_button.dart
This PR fixes the inconsistent implementation of undo duration functionality across different alarm deletion methods. It ensures that the user-set undo duration is properly applied for single alarm deletion (both swipe and menu) and adds undo functionality for multi-select deletion.
1. Fixed swipe-to-delete implementation
2. Added undo functionality to multi-select deletion
3. Fixed selection tracking in ToggleButton
https://github.com/user-attachments/assets/daadad93-29e5-4a82-a310-da2ce3a575f4
=>  Fix: Consistent Undo Duration Implementation Across All Deletion Methods

lib/app/modules/addOrUpdateAlarm/controllers/input_time_controller.dart, lib/app/modules/timer/views/timer_view.dart
Now, The input text field is getting updated after setting the timer
- Updating the Input Field after a timer is created
- Setting the timer initially to 1 minute which is same as the number picker
https://github.com/user-attachments/assets/3bdfd61e-bff9-48a8-8293-b360a5dcdc56
=> Add fix: Timer Duration is now updated with Input Field

lib/app/modules/timer/views/timer_animation.dart
There was an overflow of play and pause timer button.
- got the dimensions and
- reduced the button size accordingly for all screens.
=> fix: overflow of timer button

lib/app/data/providers/secure_storage_provider.dart, lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/settings/controllers/settings_controller.dart, lib/app/modules/settings/views/enable_flip_to_snooze.dart, lib/app/modules/settings/views/settings_view.dart, pubspec.yaml
This PR introduces the **Flip to Snooze** feature, allowing users to snooze alarms by flipping their device. Since this is a frequently used feature in alarm apps, I’ve ensured it is well-tested and configurable in the settings, with a default value of `false`.  
- Added **Flip to Snooze** functionality using device motion sensors.  
- Made the feature configurable under settings (default: `false`).  
- Ensured smooth user experience by handling edge cases.  
- Fully tested for reliability and responsiveness.  
_(This PR resolves issue #688)_  
https://github.com/user-attachments/assets/95aefd35-9697-4c85-8008-1af1548d501b
=> feat: Added flip to snooze

lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
This update improves the UI by dynamically adjusting the width of the trailing Container using MediaQuery instead of a fixed width. This ensures better responsiveness across different screen sizes.
-  Replaced the hardcoded width: 50 with MediaQuery.of(context).size.width * 0.XX to make the UI adaptable.
-  Ensured text remains aligned and does not overflow on smaller screens.
-  Maintained proper styling and readability for different weather states.
-  Enhances UI scalability across devices.
-  Improves readability for long weather type names.
-  Prevents overflow issues on smaller screens.
Let me know if you need any refinements!
=> Width changed

lib/app/data/models/alarm_model.dart, lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/alarmRing/views/alarm_ring_view.dart, lib/app/modules/home/views/home_view.dart
This PR fixes an issue where the **Exit Preview** button was incorrectly visible during both the alarm **preview** and when the alarm was actively **ringing**. This unintended behavior has now been corrected.  
Now, the **Exit Preview** button is **only visible in preview mode** and is **hidden** when the alarm is ringing. This improves the user experience by ensuring that the button does not appear in unnecessary situations.  
✅ The **Exit Preview** button now appears **only** in preview mode.  
❌ It is **no longer visible** when the alarm is ringing.  
🛠 Updated the UI logic to properly manage button visibility.  
Fixes #778  
Below are the screen recordings demonstrating the issue **before and after** the fix:  
[🔗 Video Link](https://github.com/user-attachments/assets/f1c0992a-006a-439 …
=> Fix Exit Preview Button Visibility During Alarm Ringing

lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/alarmRing/views/alarm_ring_view.dart, lib/app/modules/splashScreen/controllers/splash_screen_controller.dart
When setting an alarm with repeat = never (one-time alarm), the alarm remains enabled after it rings instead of being automatically disabled. This causes the alarm to potentially ring again on subsequent days, which is not the expected behavior for a one-time alarm.
1. Consolidated the one-time alarm handling logic in `alarm_ring_controller.dart`:
- Added proper handling of one-time alarm dismissal in the `onClose` method
- Ensures the alarm is disabled and updated in the database when dismissed
2. Removed duplicate one-time alarm handling from `splash_screen_controller.dart`:
- Removed redundant code that was trying to handle one-time alarms during app startup
- This prevents race conditions and ensures consistent behavior
https://github.com/user-attachments/assets/02f94e4b-5367-4138-8782 …
=> Fix: One-time alarms remain enabled after ringing

lib/app/modules/alarmRing/views/alarm_ring_view.dart, lib/app/modules/bottomNavigationBar/views/bottom_navigation_bar_view.dart
This PR solves the  preview screen, the app is supposed to navigate back to the home page. However, clicking the "Exit Preview" button currently results in an error page instead.
it is fixed now 
alarm_ring_view.dart
used offAllNamed()
https://github.com/user-attachments/assets/e6d1ccb2-b066-4730-b1e5-d54d986cf98f
=> fix : Exiting Preview Shows Error Page

lib/app/modules/addOrUpdateAlarm/views/guardian_angel.dart
Fixes: #785
This PR fixes an issue where toggling the **Guardian Angel switch ON** did not open the **mobile number popup**, leading to inconsistent behavior. The popup should now appear both when:  
- Clicking the **"Guardian Angel"** text.  
- Toggling the **Guardian Angel switch ON**.  
- Extracted popup logic into a separate function: `showGuardianDialog()`.  
- Updated the switch's `onChanged` handler to:  
- **Show the popup when turning ON**.  
- **Clear guardian data when turning OFF**.  
1. Navigate to the **Guardian Angel** page.  
2. Click on **"Guardian Angel"** text → ✅ Popup should appear.  
3. Toggle the **Guardian Angel switch ON** → ✅ Popup should appear.  
4. Toggle the **Guardian Angel switch OFF** → ✅ Guardian data should reset.  
before : …
=> Guardian Angel Switch Now Opens Mobile Number Popup  

lib/app/modules/addOrUpdateAlarm/views/snooze_duration_tile.dart
The snooze duration NumberPicker starts from 1 (minute) which cannot be selected from first attempt (as shown in first video). Also, user cannot disable snooze after setting it because the minimum choice is 1. 
Make the list start from 0 (off state) to to add snooze disabling functionality. Also, this is better ux-wise as compared to 1 as initial state which does not get selected even after pressing Done 
Before:
https://github.com/user-attachments/assets/ec529f43-11a3-4e27-a243-5aa3c5dc010e
After:
https://github.com/user-attachments/assets/0365ed34-e467-4480-ae26-61f6dc460220
=> Improve snooze duration list ux

lib/app/modules/alarmRing/views/alarm_ring_view.dart
This PR solves the dismiss screen, the app is supposed to navigate back to the home page. However, clicking the "Exit Preview" button currently results in an error page instead.
it is fixed now
alarm_ring_view.dart
used offAllNamed()
=> fix:Dismiss shows error 

lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
Fixed app crashing bug on create profile with an existing name
- Added file name check for identical profile names that already exists
- Added check for empty profile name
- Added Snackbars for better user experience
https://github.com/user-attachments/assets/c5af0a56-52ef-4397-8a8e-3711bde1da74
=> Add file name checks on create profile

lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart
When an alarm with deleteAfterGoesOff enabled is dismissed, the system was correctly initiating deletion but then continuing to update the same alarm, causing inconsistent behavior. Log analysis showed "Alarm deleted" followed immediately by "Alarm updated" messages.
Added early returns after successful alarm deletion to prevent execution from continuing to the update logic
Added proper try/catch blocks around database operations
Ensured awaiting of async operations to prevent race conditions
Fixed alarm deletion logic to ensure one-time alarms with deleteAfterGoesOff enabled are properly deleted when dismissed
Added early returns after deletion operations to prevent conflicting database operations
Ensured proper asynchronous execution with await keywords on database operations …
=> Fix alarm deletion issues: Prevent update after deletion when dismissing alarms

lib/app/modules/settings/views/customize_undo_duration.dart
This PR fixes issue #555 by updating the arrow styling in the Undo Duration settings tile to be consistent with other arrow elements in the app.
- Changed the icon from `Icons.chevron_right` to `Icons.arrow_forward_ios`
- Added appropriate size (18) for better proportions
- Updated the icon color from `primaryDisabledTextColor` to `primaryTextColor.value.withOpacity(0.8)`
before
after
Fixes #555
=> Fix: Arrow styling consistency in Undo Duration settings tile

lib/app/data/models/alarm_model.dart, lib/app/data/models/alarm_model.g.dart, lib/app/data/providers/isar_provider.dart, lib/app/modules/addOrUpdateAlarm/controllers/add_or_update_alarm_controller.dart, lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart, lib/app/modules/addOrUpdateAlarm/views/max_snooze_count_tile.dart, lib/app/modules/addOrUpdateAlarm/views/snooze_settings_tile.dart, lib/app/modules/alarmRing/controllers/alarm_ring_controller.dart, lib/app/modules/alarmRing/views/alarm_ring_view.dart, lib/app/modules/splashScreen/controllers/splash_screen_controller.dart, lib/app/utils/utils.dart
This PR fixes the issue with the maxSnoozeCount setting not being properly saved and retrieved from the database.
-Added the maxSnoozeCount column to the SQLite database schema in IsarDb.onCreate
-Updated the Isar database schema by regenerating it using build_runner
-Added a database fix routine (fixMaxSnoozeCountInAlarms) that ensures all alarms have the correct maxSnoozeCount value
-Added code in AlarmRingController to verify and ensure the maxSnoozeCount is correctly loaded from the database
-Fixed the startSnooze method to properly check against the actual maxSnoozeCount from the database
-Ensured the value is correctly passed through all necessary components
https://github.com/user-attachments/assets/0d91727a-bc0e-457b-b58f-48cdf6dded63
=> maxSnoozeCount Feature Implementation
